name: Auto-generate map and homepage

on:
  push:
    paths:
      - '2025-*/**.gpx'
      - 'scripts/**.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install gpxpy folium geopy

      - name: Generate all maps (from generate_map.py)
        run: python scripts/generate_map.py

      - name: Generate homepage
        run: python generate_home.py

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-generate map and homepage" || echo "No changes to commit"
          git push
